services:
  - type: web
    name: text-to-speech-webapp
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000