services:
  - type: web
    name: text-to-speech-webapp
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.9"